Repository codestates-seb/seb45_main_005, pull requests merged in 2023-09, with the labels that each got.

#31 Be/feat/community/#15
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/seb45_main_005.iml
  .idea/vcs.xml
  Server/musicforecast/build.gradle
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/audit/Auditable.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/controller/CommentController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/dto/CommentPatchDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/dto/CommentPostDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/dto/CommentResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/entity/Comment.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/mapper/CommentMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/repository/CommentRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/service/CommentService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/controller/PostController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/MultiResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PageInfo.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostPatchDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostPostDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostVoteDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/SingleResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/entity/Post.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/mapper/PostMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/repository/PostRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/service/PostService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/postTag/entity/PostTag.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/tag/entity/Tag.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/global/exception/ExceptionCode.java
Labels: Bare Minimum, [BE] 임석현

#32 Be/feat/playlist/#12
  Server/musicforecast/build.gradle
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/keyword/entity/Keyword.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/keyword/repository/KeywordRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/keyword/service/KeywordService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/Utils.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/controller/PlaylistController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/dto/PlaylistDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/entity/Playlist.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/mapper/PlaylistMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/repository/PlaylistRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/service/PlaylistService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistLike/entity/PlaylistLike.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistLike/repository/PlaylistLikeRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistLike/service/PlaylistLikeService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistSong/entity/PlaylistSong.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistSong/repository/PlaylistSongRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistSong/service/PlaylistSongService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistTag/entity/PlaylistTag.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistTag/repository/PlaylistTagRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistTag/service/PlaylistTagService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/controller/SongController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/dto/SongDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/entity/Song.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/mapper/SongMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/repository/SongRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/service/SongService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/spotify/SpotifyController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/spotify/SpotifyMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/spotify/SpotifySearchResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/spotify/SpotifyService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/spotify/SpotifyToken.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/tag/controller/TagController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/tag/dto/TagDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/tag/entity/Tag.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/tag/mapper/TagMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/tag/repository/TagRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/tag/service/TagService.java
Labels: Bare Minimum, [BE] 나수현

#34 be/feat/community/#15
  .idea/jarRepositories.xml
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/MemberResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/repository/MemberRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/service/MemberService.java
Labels: Bare Minimum, [BE] 임석현

#35 Be/feat/signup/#14
  Server/musicforecast/build.gradle
  Server/musicforecast/src/main/java/mainproject/musicforecast/config/SecurityConfiguration.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/filter/JwtAuthenticationFilter.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/handler/MemberAuthenticationFailureHandler.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/handler/MemberAuthenticationSuccessHandler.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/jwt/JwtTokenizer.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/memberdetails/MemberDetailsService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/utils/CustomAuthorityUtils.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/controller/MemberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/LoginDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/MemberPostDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/MemberResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/entity/Member.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/repository/MemberRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/service/MemberService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/mapper/PostMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/global/exception/ExceptionCode.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/global/exception/response/ErrorResponse.java
  Server/musicforecast/src/main/resources/application.yml
Labels: Bare Minimum, [BE] 전수은

#37 :sparkles: [feat] : jwt 자격 증명, 검증 구현
  Server/musicforecast/src/main/java/mainproject/musicforecast/config/SecurityConfiguration.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/filter/JwtVerificationFilter.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/handler/MemberAccessDeniedHandler.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/handler/MemberAuthenticationEntryPoint.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/utils/ErrorResponder.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/controller/MemberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/service/MemberService.java
Labels: Bare Minimum, [BE] 전수은

#38 Be/feat/signup/#14
  Server/musicforecast/src/main/java/mainproject/musicforecast/config/SecurityConfiguration.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/filter/JwtAuthenticationFilter.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/filter/JwtVerificationFilter.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/handler/MemberAuthenticationFailureHandler.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/controller/MemberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/service/MemberService.java
Labels: Bare Minimum, [BE] 전수은

#39 Be/feat/recommend/#26
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/controller/PlaylistController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/repository/PlaylistRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/service/PlaylistService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistLike/service/PlaylistLikeService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistSong/service/PlaylistSongService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/weather/WeatherController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/weather/WeatherDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/weather/WeatherService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/controller/SongController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/spotify/SpotifyService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/spotify/SpotifyToken.java
  Server/musicforecast/src/main/resources/application.yml
Labels: Bare Minimum, [BE] 나수현

#47 ✨feat:login, 회원가입 기능 구현
  Client/.eslintrc.js
  Client/package-lock.json
  Client/package.json
  Client/src/assets/images/google.svg
  Client/src/components/Login/GoogleOauth.tsx
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Login/SignUp.tsx
  Client/src/components/Main/Chart.tsx
  Client/src/components/Main/Contents.tsx
  Client/src/components/Main/Footer.tsx
  Client/src/components/Main/Main.tsx
  Client/src/components/Main/MainHead.tsx
  Client/src/index.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/tsconfig.json
Labels: Bare Minimum, [FE] 진종환

#50 Be/feat/recommend/#26
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/repository/PlaylistRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistSong/entity/PlaylistSong.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistTag/repository/PlaylistTagRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/mubti/MubtiController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/mubti/MubtiService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/weather/WeatherController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/weather/WeatherService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/youtuber/Youtuber.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/youtuber/YoutuberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/youtuber/YoutuberMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/youtuber/YoutuberRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/youtuber/YoutuberResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/youtuber/YoutuberService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/controller/SongController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/repository/SongRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/service/SongService.java
Labels: Bare Minimum, [BE] 나수현

#51 Be/feat/community/#15
  .idea/compiler.xml
  .idea/modules.xml
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/mapper/PostMapper.java
Labels: Bare Minimum, [BE] 임석현

#55 Be/feat/signup/#14
  .idea/modules.xml
  Server/musicforecast/src/main/java/mainproject/musicforecast/config/SecurityConfiguration.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/filter/JwtAuthenticationFilter.java
Labels: Bare Minimum, [BE] 전수은

#56 Be/feat/community/#15
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules/musicforecast.main.iml
  .idea/modules/musicforecast.test.iml
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/controller/PostController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/repository/PostRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/service/PostService.java
Labels: Bare Minimum, [BE] 임석현

#57 Be/feat/recommend/#26
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/controller/PlaylistController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/mapper/PlaylistMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistLike/service/PlaylistLikeService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/mapper/PostMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/service/SongService.java
Labels: Bare Minimum, [BE] 나수현

#58 fix: memberId 삭제
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/dto/PlaylistDto.java
Labels: Bare Minimum, [BE] 나수현

#64 ✨feat:login, 회원가입 기능 구현
  Client/package-lock.json
  Client/package.json
  Client/src/components/Login/GoogleOauth.tsx
  Client/src/components/Login/KakaoLogin.tsx
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Main/Contents.tsx
  Client/src/components/Main/Footer.tsx
  Client/src/components/Main/MainHead.tsx
  Client/src/index.tsx
  Client/src/redux/Slice/LoginSlice.ts
Labels: Bare Minimum, [FE] 진종환

#65 ✨feat:login, 회원가입 기능 구현
  Client/src/components/Login/KakaoLogin.tsx
Labels: Bare Minimum, [FE] 진종환

#70 Fe/feat/song search/#63
  Client/src/components/Modal/SongAddModal.tsx
  Client/src/components/Search/SongInfo.tsx
  Client/src/components/Search/Songlists.tsx
  Client/src/index.css
  Client/src/redux/slice/SonglistsSlice.ts
Labels: Bare Minimum, [FE] 이인우

#71 Be/feat/mainpage/#25
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/mainpage/controller/MainpageController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/mainpage/repository/MainpageRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/mainpage/service/MainpageService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/controller/PlaylistController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/repository/PlaylistRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/service/PlaylistService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/admin/AdminController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/admin/AdminMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/admin/AdminRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/admin/AdminResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/admin/AdminService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/admin/AdminSuggest.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/mubti/MubtiController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/mubti/MubtiService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/controller/SongController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/dto/SongDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/mapper/SongMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/repository/SongRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/service/SongService.java
Labels: Bare Minimum, [BE] 나수현

#73 ✨ feat: 노래 검색 및 노래 선택 시 추가 기능 구현
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Modal/PlaylistModal.tsx
  Client/src/components/Modal/SongAddModal.tsx
  Client/src/components/Playlist/PlayListsDetail.tsx
  Client/src/components/Playlist/Playlists.tsx
  Client/src/components/Playlist/PlaylistsShowAll.tsx
  Client/src/components/Search/Button/SongBtn.tsx
  Client/src/components/Search/SearchInput.tsx
  Client/src/components/Search/SongInfo.tsx
  Client/src/components/Search/Songlists.tsx
  Client/src/components/WeatherRecommendation/Weather.tsx
  Client/src/redux/slice/ModalSlice.ts
  Client/src/redux/slice/SonglistsSlice.ts
Labels: Bare Minimum, [FE] 이인우

#76 Be/feat/mainpage/#25
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/mainpage/controller/MainpageController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/dto/PlaylistDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/mapper/PlaylistMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/service/PlaylistService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistTag/entity/PlaylistTag.java
Labels: Bare Minimum, [BE] 나수현

#77 Be/feat/signup/#14
  Server/musicforecast/src/main/java/mainproject/musicforecast/config/SecurityConfiguration.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/controller/FindMemberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/controller/MemberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/FindMemberDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/mapper/MemberMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/service/FindMemberService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/service/MemberService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/oauth2_jwt/auth/handler/OAuth2MemberSuccessHandler.java
Labels: Bare Minimum, [BE] 전수은

#78 Be/feat/community/#15
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/musicforecast.test.iml
  .idea/uiDesigner.xml
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/service/PlaylistService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/controller/PostController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/Like.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostVoteDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/entity/Post.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/mapper/PostMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/repository/PostRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/service/PostService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/postLike/entity/PostLike.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/postLike/repository/PostLikeRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/postLike/service/PostLikeService.java
Labels: Bare Minimum, [BE] 임석현

#80 fix: 헤더,게시판,마이페이지수정
  Client/src/components/Header.tsx
  Client/src/components/Login/LoginOn.tsx
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/MUBTI/MUBTIMain.tsx
  Client/src/pages/Mypage.tsx
  Client/src/pages/Write.tsx
  Client/src/redux/slice/CommunitySlice.ts
  Client/src/redux/slice/LoginSlice.ts
Labels: Bare Minimum, [FE] 김진현

#81 :sparkles: [feat] : Header에 nickname 추가
  .idea/modules/musicforecast.test.iml
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/filter/JwtAuthenticationFilter.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/memberdetails/MemberDetailsService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/oauth2_jwt/auth/handler/OAuth2MemberSuccessHandler.java
  Server/musicforecast/src/main/resources/application.yml
Labels: Bare Minimum, [BE] 전수은

#82 Be/feat/mainpage/#25
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/service/PlaylistService.java
Labels: Bare Minimum, [BE] 나수현

#83 :sparkles: feat:게시글 댓글작성 및 열람
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
Labels: Bare Minimum, [FE] 김진현

#84 Fe dev design: 📱 목업 수정
  Client/package-lock.json
  Client/package.json
  Client/src/App.tsx
  Client/src/assets/images/main.jpeg
  Client/src/components/Login/GoogleOauth.tsx
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Login/SignUp.tsx
  Client/src/components/Styles/animation.ts
  Client/src/components/Wrapper/Wrapper.tsx
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/EditProfile.tsx
  Client/src/pages/MUBTI/MUBTIMain.tsx
  Client/src/pages/Mypage.tsx
  Client/src/pages/SearchSongs.tsx
  Client/src/pages/WeatherRecommend.tsx
  Client/src/pages/Write.tsx
Labels: Bare Minimum, [FE] 진종환

#85 ✨feat:목업 수정
  Client/src/App.tsx
  Client/src/components/Header.tsx
  Client/src/components/Main/Chart.tsx
  Client/src/components/Main/Contents.tsx
  Client/src/components/Main/Main.tsx
  Client/src/components/Styles/animation.ts
Labels: Bare Minimum, [FE] 진종환

#86 [FE] 📱feat:목업 수정
  Client/src/components/Main/Chart.tsx
Labels: Bare Minimum, [FE] 진종환

#87 :sparkles: feat: 게시판 플레이리시트용 음악검색
  Client/src/components/Login/LoginOn.tsx
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/Write.tsx
Labels: Bare Minimum, [FE] 김진현

#90 ✨ fe/feat: 마이플레이리스트 조회
  Client/src/components/Header.tsx
  Client/src/components/Modal/PlaylistModal.tsx
  Client/src/components/Playlist/Button/PlaylistUpdateBtn.tsx
  Client/src/components/Playlist/MyPlaylists.tsx
  Client/src/components/Playlist/MyPlaylistsShowAll.tsx
  Client/src/components/Playlist/PlayListsDetail.tsx
  Client/src/components/WeatherRecommendation/Button/WeatherChange.tsx
  Client/src/components/WeatherRecommendation/ContentBox.tsx
  Client/src/components/WeatherRecommendation/Genre/RecommendLists.tsx
  Client/src/components/WeatherRecommendation/Weather.tsx
  Client/src/redux/slice/ModalSlice.ts
  Client/src/redux/slice/PlaylistsSlice.ts
  Client/src/redux/slice/WeatherSlice.ts
  Client/src/redux/store.ts
Labels: Bare Minimum, [FE] 이인우

#92 :bug: bug: 렌더링 오류 수정
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Modal/PlaylistModal.tsx
  Client/src/components/Modal/SongAddModal.tsx
  Client/src/components/Modal/ToastModal.tsx
  Client/src/components/Playlist/Button/PlaylistUpdateBtn.tsx
  Client/src/components/Playlist/Button/SongDeleteBtn.tsx
  Client/src/components/Playlist/MyPlaylists.tsx
  Client/src/components/Playlist/MyPlaylistsShowAll.tsx
  Client/src/components/Playlist/PlayListsDetail.tsx
  Client/src/components/Playlist/Playlists.tsx
  Client/src/components/Playlist/PlaylistsShowAll.tsx
  Client/src/components/Search/Songlists.tsx
  Client/src/pages/Mypage.tsx
  Client/src/redux/slice/PlaylistCRUDSlice.ts
  Client/src/redux/slice/PlaylistsSlice.ts
  Client/src/redux/slice/SonglistsSlice.ts
Labels: Bug, [FE] 이인우

#97 Be/feat/mainpage/#25
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/dto/PlaylistDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/mapper/PlaylistMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistSong/entity/PlaylistSong.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/mubti/MubtiService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/weather/WeatherService.java
Labels: Bare Minimum, [BE] 나수현

#98 ✨feat:노래 재생 플레이어 기능 추가
  Client/package-lock.json
  Client/package.json
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Login/SignUp.tsx
  Client/src/components/Main/Data/data.json
  Client/src/components/Main/MbtiMain.tsx
  Client/src/components/Main/Motherplayer.tsx
  Client/src/components/Main/Plyer.tsx
Labels: Bare Minimum, [FE] 진종환

#102 :sparkles: feat:게시판 수정폼
  Client/src/App.tsx
  Client/src/components/Main/Plyer.tsx
  Client/src/interface/RouteConst.js
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/CommunityEdit.tsx
Labels: Bare Minimum, [FE] 김진현

#104 반응형 도전
  Client/src/components/Main/Plyer.tsx
  Client/src/components/Playlist/PlaylistIcon.tsx
  Client/src/components/WeatherRecommendation/ContentBox.tsx
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/EditProfile.tsx
Labels: Bare Minimum, [FE] 김진현

#107 [Fe] ✨feat: id,pw 찾기 목업 수정
  Client/src/components/Login/IdFind.tsx
  Client/src/components/Login/PwdFind.tsx
  Client/src/components/Login/SignUp.tsx
  Client/src/components/Main/Contents.tsx
  Client/src/components/Main/MbtiMain.tsx
  Client/src/components/Main/Songfind.tsx
  Client/src/components/Main/TechStack.tsx
  Client/src/components/WeatherRecommendation/Weather.tsx
  Client/src/interface/PrivateRoute.js
Labels: Advanced Challenge, [FE] 진종환

#109 Be/feat/community/#15
  .idea/modules.xml
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/controller/CommentController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/controller/PostController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostPatchDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/mapper/PostMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/service/PostService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/reply/controller/ReplyController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/reply/entity/Reply.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/reply/repository/ReplyRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/reply/service/ReplyService.java
Labels: Bare Minimum, [BE] 임석현

#110 Be/feat/mainpage/#25
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/mubti/MubtiService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/recommend/weather/WeatherService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/controller/SongController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/repository/SongRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/song/service/SongService.java
Labels: Bare Minimum, [BE] 나수현

#111 :sparkles: feat:MUBTI기능추가
  Client/src/App.tsx
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Login/SignUp.tsx
  Client/src/components/Login/Test.tsx
  Client/src/components/Main/Plyer.tsx
  Client/src/components/Modal/PlaylistModal.tsx
  Client/src/components/Modal/SongAddModal.tsx
  Client/src/components/Modal/ToastModal.tsx
  Client/src/components/Playlist/Button/PlaylistUpdateBtn.tsx
  Client/src/components/Playlist/Button/SongDeleteBtn.tsx
  Client/src/components/Playlist/MyPlaylists.tsx
  Client/src/components/Playlist/PlayListsDetail.tsx
  Client/src/components/Playlist/PlaylistsShowAll.tsx
  Client/src/components/Search/Button/SongBtn.tsx
  Client/src/components/Search/SearchInput.tsx
  Client/src/components/WeatherRecommendation/Genre/RecommendLists.tsx
  Client/src/components/WeatherRecommendation/Weather.tsx
  Client/src/interface/RouteConst.js
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/CommunityEdit.tsx
  Client/src/pages/EditProfile.tsx
  Client/src/pages/MUBTI/Survey/Survey.tsx
  Client/src/pages/MUBTI/Survey/SurveyLiking.tsx
  Client/src/pages/MUBTI/Survey/SurveyLoading.tsx
  Client/src/pages/MUBTI/Survey/SurveyYoutube.tsx
  Client/src/pages/Mypage.tsx
  Client/src/pages/Write.tsx
  Client/vercel.json
Labels: Bare Minimum, [FE] 이인우, [FE] 김진현, [FE] 진종환

#112 Be/feat/community/#15
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/controller/PostController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostPostDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/mapper/PostMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/repository/PostRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/service/PostService.java
Labels: Bare Minimum, [BE] 임석현

#113 Be/feat/signup/#14
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/controller/FindMemberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/controller/MemberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/FindMemberDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/repository/MemberRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/service/FindMemberService.java
  Server/musicforecast/src/main/resources/application.yml
Labels: Bare Minimum, [BE] 전수은

#116 ✨ feat: 플레이리스트 검색 및 좋아요/#114
  Client/public/favicon.ico
  Client/public/index.html
  Client/src/assets/images/AlbumFirst.png
  Client/src/components/Modal/PlaylistModal.tsx
  Client/src/components/Modal/SongAddModal.tsx
  Client/src/components/Modal/ToastModal.tsx
  Client/src/components/Playlist/Button/PlaylistLiketBtn.tsx
  Client/src/components/Playlist/Button/PlaylistUpdateBtn.tsx
  Client/src/components/Playlist/MyPlaylists.tsx
  Client/src/components/Playlist/MyPlaylistsShowAll.tsx
  Client/src/components/Playlist/PlayListsDetail.tsx
  Client/src/components/Playlist/Playlists.tsx
  Client/src/components/Playlist/PlaylistsSearch.tsx
  Client/src/components/Playlist/PlaylistsShowAll.tsx
  Client/src/components/Playlist/SearchedPlaylists.tsx
  Client/src/components/Search/SongInfo.tsx
  Client/src/components/Search/Songlists.tsx
  Client/src/components/WeatherRecommendation/Button/WeatherChange.tsx
  Client/src/components/WeatherRecommendation/ContentBox.tsx
  Client/src/components/WeatherRecommendation/Genre/RecommendLists.tsx
  Client/src/components/WeatherRecommendation/Weather.tsx
  Client/src/pages/WeatherRecommend.tsx
  Client/src/redux/slice/LoginSlice.ts
  Client/src/redux/slice/ModalSlice.ts
  Client/src/redux/slice/PlaylistsSlice.ts
  Client/tailwind.config.js
Labels: Bare Minimum, [FE] 이인우

#117 :sparkles: feat:게시판 상세페이지, 글쓰기
  Client/src/components/Login/Test.tsx
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/Write.tsx
Labels: Bare Minimum, [FE] 김진현

#118 [Fe] ✨feat: oauth 기능 수정
  Client/src/components/Login/GoogleOauth.tsx
  Client/src/components/Login/IdFind.tsx
  Client/src/components/Login/KakaoLogin.tsx
  Client/src/components/Login/Kakaobt.tsx
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Login/PwdFind.tsx
  Client/src/components/Profile.tsx
  Client/src/pages/EditProfile.tsx
Labels: Advanced Challenge, [FE] 진종환

#119 [Fe] ✨feat: 아이디, 비밀번호 찾기 로직 수정
  Client/src/App.tsx
  Client/src/components/Login/Kakaobt.tsx
  Client/src/components/Login/PwdChange.tsx
  Client/src/components/Login/PwdFind.tsx
  Client/src/interface/RouteConst.js
Labels: Advanced Challenge, [FE] 진종환

#120 콘솔로그삭제
  Client/src/App.tsx
  Client/src/components/Header.tsx
  Client/src/components/Login/GoogleOauth.tsx
  Client/src/components/Login/IdFind.tsx
  Client/src/components/Login/Kakaobt.tsx
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Login/PwdFind.tsx
  Client/src/components/Login/SignUp.tsx
  Client/src/components/Main/Contents.tsx
  Client/src/components/Main/Plyer.tsx
  Client/src/components/MyCommunity.tsx
  Client/src/components/MyPlayList.tsx
  Client/src/components/Search/SearchInput.tsx
  Client/src/index.tsx
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/CommunityEdit.tsx
  Client/src/pages/MUBTI/MUBTIMain.tsx
  Client/src/pages/MUBTI/Survey/Survey.tsx
  Client/src/pages/MUBTI/Survey/SurveyLiking.tsx
  Client/src/pages/MUBTI/Survey/SurveyLoading.tsx
  Client/src/pages/MUBTI/Survey/SurveyMood.tsx
  Client/src/pages/MUBTI/Survey/SurveySituation.tsx
  Client/src/pages/MUBTI/Survey/SurveyYoutube.tsx
  Client/src/pages/Mypage.tsx
  Client/src/pages/Write.tsx
Labels: Bare Minimum, [FE] 이인우, [FE] 김진현, [FE] 진종환

#121 be/feat/community/#15
  Server/musicforecast/src/main/java/mainproject/musicforecast/config/SecurityConfiguration.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/controller/PostController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/dto/PostResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/entity/Post.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/post/mapper/PostMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/postLike/service/PostLikeService.java
Labels: Bare Minimum, [BE] 임석현

#122 Be/feat/signup/#14
  Server/musicforecast/src/main/java/mainproject/musicforecast/config/SecurityConfiguration.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/kakao/Controller/OauthController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/kakao/Service/KakaoOauthService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/kakao/Service/OauthService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/controller/FindMemberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/FindMemberDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/FindQuestionDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/FindUsernameDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/QuestionResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/UpdatePwDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/dto/UsernameResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/entity/Member.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/mapper/MemberMapper.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/repository/MemberRepository.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/service/FindMemberService.java
Labels: Bare Minimum, [BE] 전수은

#123 Be/feat/mainpage/#25
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/controller/PlaylistController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/dto/PlaylistDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistLike/service/PlaylistLikeService.java
Labels: Bare Minimum, [BE] 나수현

#126 ✨feat: toast 기능 추가
  Client/src/App.tsx
  Client/src/components/Header.tsx
  Client/src/components/Login/Kakaobt.tsx
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Modal/ToastModal.tsx
  Client/src/index.tsx
  Client/src/interface/PrivateRoute.js
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/Write.tsx
Labels: Advanced Challenge, [FE] 진종환

#124 :sparkles: [feat] : 회원 탈퇴 url 수정
  Server/musicforecast/src/main/java/mainproject/musicforecast/config/SecurityConfiguration.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/authQuestion/entity/AuthQuestion.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/kakao/Controller/OauthController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/kakao/Service/KakaoOauthService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/auth/kakao/entity/KakaoMember.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/controller/MemberController.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/member/service/MemberService.java
  Server/musicforecast/src/main/resources/application.yml
Labels: Bare Minimum, [BE] 전수은

#130 Be/feat/community/#15
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/dto/CommentPatchDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/dto/CommentPostDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/dto/CommentResponseDto.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/entity/Comment.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/comment/service/CommentService.java
Labels: Bare Minimum, [BE] 임석현

#131 fix: member id 비교
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/service/PlaylistService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistSong/service/PlaylistSongService.java
Labels: Bare Minimum, [BE] 나수현

#132 fix: equals
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlist/service/PlaylistService.java
  Server/musicforecast/src/main/java/mainproject/musicforecast/domain/playlistSong/service/PlaylistSongService.java
Labels: Bare Minimum, [BE] 나수현

#133 배포용 디자인
  .DS_Store
  Client/src/assets/images/modalbox.png
  Client/src/assets/images/modalbox2-removebg-preview.png
  Client/src/assets/images/turndisk.png
  Client/src/assets/images/turntable.png
  Client/src/components/Login/SignUp.tsx
  Client/src/components/Modal/PlaylistModal.tsx
  Client/src/components/Modal/SongAddModal.tsx
  Client/src/components/Modal/ToastModal.tsx
  Client/src/components/Playlist/Button/PlaylistUpdateBtn.tsx
  Client/src/components/Playlist/MyPlaylists.tsx
  Client/src/components/Playlist/MyPlaylistsShowAll.tsx
  Client/src/components/Playlist/PlayListsDetail.tsx
  Client/src/components/Playlist/PlaylistIcon.tsx
  Client/src/components/Playlist/Playlists.tsx
  Client/src/components/Playlist/PlaylistsSearch.tsx
  Client/src/components/Playlist/PlaylistsShowAll.tsx
  Client/src/components/Search/Button/SongBtn.tsx
  Client/src/components/Search/SongInfo.tsx
  Client/src/components/Search/Songlists.tsx
  Client/src/components/WeatherRecommendation/ContentBox.tsx
  Client/src/components/WeatherRecommendation/Genre/RecommendLists.tsx
  Client/src/pages/Community.tsx
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/SearchSongs.tsx
  Client/src/pages/Write.tsx
  Client/tailwind.config.js
Labels: Bare Minimum, [FE] 이인우, [FE] 김진현, [FE] 진종환

#134 [Fe] ✨feat: 로그인 기능 수정
  Client/src/components/Header.tsx
  Client/src/components/Login/GoogleOauth.tsx
  Client/src/components/Login/Kakaobt.tsx
  Client/src/components/Login/LoginOn.tsx
  Client/src/components/Login/SignUp.tsx
  Client/src/redux/slice/LoginSlice.ts
Labels: Bare Minimum, [FE] 진종환

#135 [FE] ✨feat: Oauth로그인 기능 수정
  Client/src/components/Login/GoogleOauth.tsx
  Client/src/components/Login/Kakaobt.tsx
Labels: Bare Minimum, [FE] 진종환

#136 최종배포
  Client/src/App.tsx
  Client/src/components/Main/Data/data.json
  Client/src/components/Main/MbtiMain.tsx
  Client/src/components/Main/Plyer.tsx
  Client/src/components/Modal/RecommendAdd.tsx
  Client/src/components/Playlist/Button/MyPliAddSongbtn.tsx
  Client/src/components/Playlist/PlayListsDetail.tsx
  Client/src/interface/RouteConst.js
  Client/src/pages/CommunityDetail.tsx
  Client/src/pages/CommunityEdit.tsx
  Client/src/pages/MUBTI/Survey/SurveyAdmin.tsx
  Client/src/pages/MUBTI/Survey/SurveyLiking.tsx
  Client/src/pages/Write.tsx
  Client/src/redux/slice/ModalSlice.ts
  Client/tailwind.config.js
Labels: Bare Minimum, [FE] 이인우, [FE] 김진현, [FE] 진종환
